name: first_flutter_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.7.2
  logger: ^2.6.1  # for logging purpose
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  get_it: ^8.2.0
  table_calendar: ^3.2.0
  hive_flutter: ^1.1.0
  custom_check_box: ^0.0.4
  flutter_slidable: ^4.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.0.5
  build_runner: ^2.8.0
  json_serializable: ^6.11.1


flutter:
  assets:
    - assets/images/
  fonts:
    - family: Poller
      fonts:
        - asset: assets/fonts/PollerOne-Regular.ttf

  uses-material-design: true
